name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  build_ios:
    name: Build Flutter (iOS)
    needs: []
    runs-on: macos-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-java@v1
        with:
          java-version: "12.x"
      - uses: spot-map/mobile@v1
        with:
            channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ipa

  build_apk:
    name: Build Flutter (Android)
    needs: []
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-java@v1
        with:
          java-version: "12.x"
      - uses: spot-map/mobile@v1
        with:
            channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk